name: Docker
on:
  schedule:
    - cron: '0 1 * * *'
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches: [ main ]
    paths:
      - 'packaging/docker/**'
jobs:
  docker-images:
    name: Docker Images
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Alpine Docker tags
        id: docker_alpine_tags
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/miniflux
          tags: |
            type=ref,event=pr
            type=schedule,pattern=nightly
            type=semver,pattern={{raw}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Alpine images
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./packaging/docker/alpine/Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_alpine_tags.outputs.tags }}
